on: 
  push:
    branches:
      - master
    paths-ignore:
      - 'dist/**'

jobs:
  build-cypress-action:
    runs-on: ubuntu-20.04
    name: Build Cypress Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update action distributable"
          body: |
            Automatic action distributable update
          commit-message: "Update action distributable"
          delete-branch: true